sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true


before_install:
  - composer selfupdate
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

install:
  - composer install

script:
  - phing -f build.xml
  - cd ../.. && php /var/www/html/drupal8/core/scripts/run-tests.sh --url http://127.0.0.1/drupal8/ --module conflict
