<?php

/**
 * @file
 * Fieldwise conflict prevention and resolution.
 * @author Brandon Bergren
 */

function conflict_form_node_form_alter(&$form, &$form_state) {
  // Force caching enabled so we can keep our base object around.
  $form_state['cache'] = TRUE;
}

/**
 * Implements hook_node_validate().
 */
function conflict_node_validate($node, &$form, &$form_state) {
  if (isset($node->nid) && (node_last_changed($node->nid) > $node->changed)) {

    // Bypass the core conflict detector.
    $errors = &drupal_static('form_set_error', array());
    if (!empty($errors['changed'])) {
      unset($errors['changed']);
      // Remove the message as well.
      foreach ($_SESSION['messages']['error'] as $k => $v) {
        if ($v == t('The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved.')) {
          unset($_SESSION['messages']['error'][$k]);
          $_SESSION['messages']['error'] = array_values($_SESSION['messages']['error']);
        }
        if (empty($_SESSION['messages']['error'])) {
          unset($_SESSION['messages']['error']);
        }
      }
    }

    $nodes = array();
    $nodes['base'] = clone($form_state['node']);
    $nodes['theirs'] = node_load($node->nid, NULL, TRUE);
    $nodes['mine'] = clone($node);

    // Dig through the fields
    $conflicting = FALSE; // Assume we can fix things unless proven otherwise.
    $updated = FALSE;
    $type = node_type_get_type($nodes['mine']);
    $instances = field_info_instances('node', field_extract_bundle('node', $type));
    foreach ($instances as $instance) {
      $field_name = $instance['field_name'];
      $langcode = field_language('node', $nodes['mine'], $field_name);
      foreach (array('base', 'theirs', 'mine') as $k) {
        $f[$k] = isset($nodes[$k]->{$field_name}[$langcode]) ? $nodes[$k]->{$field_name}[$langcode] : array();
        // Checksum the data so it's directly comparable.
        $sum[$k] = md5(serialize($f[$k]));
      }

      if ($sum['base'] == $sum['theirs']) {
        // No changes, or only mine changed.
        // We don't need to do anything about this field.
        continue;
      }
      elseif ($sum['base'] == $sum['mine']) {
        // Only theirs changed. We need to update our value.
        $value = $f['theirs'];
        form_set_value($form[$field_name], $value, $form_state);
        // Forget the user-submitted value.
        unset($form_state['input'][$field_name]);
        drupal_set_message(t('The @label field was changed by another user. Please verify the updated value.', array('@label' => $instance['label'])), 'warning');
        $updated = TRUE;
      }
      else {
        // Conflict!
        $conflicting = TRUE;
        $updated = TRUE;
        drupal_set_message(t('The @label field was changed by another user while you were editing it! Save again if you want overwrite it!', array('@label' => $instance['label'])), 'error');
      }
    }

    if ($updated) {
      // Reload the node to pick up the updated data.
      $node = clone($nodes['theirs']);
      node_object_prepare($node);
      $form_state['node'] = $node;
      $form_state['rebuild'] = TRUE;
    }
  }
}